name: Run node 20 tests
author: PPSE
description: Run the tests to the node 20 image
inputs:
  image-registry:
    description: The AWS region to authenticate into to access AWS ECR.
    required: true
    default: ap-southeast-2

runs:
  using: composite
  steps:
    - name: generate-build-nr
      id: generate-build-nr
      shell: bash
      run: echo "image-date-str=$(date +%Y%m%d%H%M%S)" >> "${GITHUB_OUTPUT}"
    - name: Test
      shell: bash
      run: echo "THE OUTPUT IS ${{ inputs.image-registry }} - ${{ steps.generate-build-nr.output.image-date-str }}"

