name: PR check

on:
  push:

permissions:
  contents: write
  # Note that this permission will not be available if the PR is from a forked repository

jobs:
  test-if-or-condition:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Current ref is: ${{ github.ref }}  and equality test result is ${{ github.ref == ('refs/heads/develop' || 'refs/heads/master' || 'pull_request') }}"
      
      - run: "echo It worked"
        if: github.ref == ('refs/heads/develop' || 'refs/heads/teste-if-or' || 'pull_request')

